-- Ejecutar una sola vez en el SQL Editor de Supabase.
-- Los lotes existentes se crean usando el stock y costo actual de cada producto.
create table if not exists public."LotesStock" (
  "idLote" bigint generated by default as identity primary key,
  "idProducto" bigint not null references public."Productos"("idProducto") on delete cascade,
  "CantidadInicial" integer not null check ("CantidadInicial" > 0),
  "CantidadDisponible" integer not null check ("CantidadDisponible" >= 0),
  "PrecioCompra" numeric not null check ("PrecioCompra" >= 0),
  "PrecioVenta" numeric not null check ("PrecioVenta" >= 0),
  "fechaIngreso" timestamptz not null default now()
);

create table if not exists public."ConsumosLote" (
  "idConsumo" bigint generated by default as identity primary key,
  "idDetalle" bigint not null references public."DetalleVentas"("idDetalle") on delete cascade,
  "idLote" bigint not null references public."LotesStock"("idLote") on delete restrict,
  "Cantidad" integer not null check ("Cantidad" > 0),
  "CostoUnitario" numeric not null check ("CostoUnitario" >= 0)
);

create index if not exists lotes_stock_fifo_idx on public."LotesStock" ("idProducto", "fechaIngreso", "idLote") where "CantidadDisponible" > 0;
create index if not exists consumos_lote_detalle_idx on public."ConsumosLote" ("idDetalle");

insert into public."LotesStock" ("idProducto", "CantidadInicial", "CantidadDisponible", "PrecioCompra", "PrecioVenta")
select p."idProducto", p."Stock", p."Stock", coalesce(p."PrecioCompra", 0), coalesce(p."PrecioVenta", 0)
from public."Productos" p
where coalesce(p."Stock", 0) > 0
  and not exists (select 1 from public."LotesStock" l where l."idProducto" = p."idProducto");

create or replace function public.agregar_lote_stock(p_id_producto bigint, p_cantidad integer, p_precio_compra numeric, p_precio_venta numeric)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_cantidad <= 0 or p_precio_compra < 0 or p_precio_venta < 0 then
    raise exception 'Los valores del lote no son válidos';
  end if;

  perform 1 from public."Productos" where "idProducto" = p_id_producto for update;
  if not found then raise exception 'Producto inexistente'; end if;

  insert into public."LotesStock" ("idProducto", "CantidadInicial", "CantidadDisponible", "PrecioCompra", "PrecioVenta")
  values (p_id_producto, p_cantidad, p_cantidad, p_precio_compra, p_precio_venta);
  update public."Productos"
  set "Stock" = coalesce("Stock", 0) + p_cantidad, "PrecioCompra" = p_precio_compra, "PrecioVenta" = p_precio_venta
  where "idProducto" = p_id_producto;
end;
$$;

create or replace function public.registrar_venta_fifo(p_id_cliente bigint, p_renglones jsonb)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_venta bigint;
  v_renglon jsonb;
  v_lote record;
  v_detalle bigint;
  v_pendiente integer;
  v_tomar integer;
  v_total numeric := 0;
begin
  if jsonb_typeof(p_renglones) <> 'array' or jsonb_array_length(p_renglones) = 0 then raise exception 'La venta debe incluir productos'; end if;
  insert into public."Ventas" ("idCliente", fecha, estado, total) values (p_id_cliente, now(), 'activa', 0) returning "idVenta" into v_venta;
  for v_renglon in select * from jsonb_array_elements(p_renglones) loop
    v_pendiente := (v_renglon->>'cantidad')::integer;
    if v_pendiente <= 0 or (v_renglon->>'precioVenta')::numeric < 0 then raise exception 'Renglón de venta inválido'; end if;
    insert into public."DetalleVentas" ("idVenta", "idProducto", "CantidadUnidades", "PrecioVentaUnitario")
    values (v_venta, (v_renglon->>'idProducto')::bigint, v_pendiente, (v_renglon->>'precioVenta')::numeric) returning "idDetalle" into v_detalle;
    for v_lote in select * from public."LotesStock" where "idProducto" = (v_renglon->>'idProducto')::bigint and "CantidadDisponible" > 0 order by "fechaIngreso", "idLote" for update loop
      exit when v_pendiente = 0;
      v_tomar := least(v_pendiente, v_lote."CantidadDisponible");
      update public."LotesStock" set "CantidadDisponible" = "CantidadDisponible" - v_tomar where "idLote" = v_lote."idLote";
      insert into public."ConsumosLote" ("idDetalle", "idLote", "Cantidad", "CostoUnitario") values (v_detalle, v_lote."idLote", v_tomar, v_lote."PrecioCompra");
      v_pendiente := v_pendiente - v_tomar;
    end loop;
    if v_pendiente > 0 then raise exception 'No hay stock suficiente para el producto %', v_renglon->>'idProducto'; end if;
    update public."Productos" set "Stock" = coalesce("Stock", 0) - (v_renglon->>'cantidad')::integer where "idProducto" = (v_renglon->>'idProducto')::bigint;
    v_total := v_total + (v_renglon->>'cantidad')::integer * (v_renglon->>'precioVenta')::numeric;
  end loop;
  update public."Ventas" set total = v_total where "idVenta" = v_venta;
  return v_venta;
end;
$$;

create or replace function public.eliminar_venta_fifo(p_id_venta bigint)
returns void language plpgsql security definer set search_path = public as $$
declare v_consumo record;
begin
  for v_consumo in select c."idLote", c."Cantidad", l."idProducto" from public."ConsumosLote" c join public."LotesStock" l on l."idLote" = c."idLote" join public."DetalleVentas" d on d."idDetalle" = c."idDetalle" where d."idVenta" = p_id_venta for update of l loop
    update public."LotesStock" set "CantidadDisponible" = "CantidadDisponible" + v_consumo."Cantidad" where "idLote" = v_consumo."idLote";
    update public."Productos" set "Stock" = coalesce("Stock", 0) + v_consumo."Cantidad" where "idProducto" = v_consumo."idProducto";
  end loop;
  delete from public."Ventas" where "idVenta" = p_id_venta;
end;
$$;

grant execute on function public.agregar_lote_stock(bigint, integer, numeric, numeric) to anon, authenticated;
grant execute on function public.registrar_venta_fifo(bigint, jsonb) to anon, authenticated;
grant execute on function public.eliminar_venta_fifo(bigint) to anon, authenticated;

-- Hace que PostgREST/Supabase detecte las funciones nuevas de inmediato.
notify pgrst, 'reload schema';
